name: Update Match Odds CSV

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests beautifulsoup4 PyGithub
        
    - name: Run update script
      env:
        SOURCE_REPO_TOKEN: ${{ secrets.SOURCE_REPO_TOKEN }}
        TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
      run: python scraping_current_week.py
